/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	v1alpha1 "projectkuryr/kuryr/pkg/apis/openstack/v1alpha1"
	scheme "projectkuryr/kuryr/pkg/client/clientset/versioned/scheme"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KuryrPortsGetter has a method to return a KuryrPortInterface.
// A group's client should implement this interface.
type KuryrPortsGetter interface {
	KuryrPorts(namespace string) KuryrPortInterface
}

// KuryrPortInterface has methods to work with KuryrPort resources.
type KuryrPortInterface interface {
	Create(ctx context.Context, kuryrPort *v1alpha1.KuryrPort, opts v1.CreateOptions) (*v1alpha1.KuryrPort, error)
	Update(ctx context.Context, kuryrPort *v1alpha1.KuryrPort, opts v1.UpdateOptions) (*v1alpha1.KuryrPort, error)
	UpdateStatus(ctx context.Context, kuryrPort *v1alpha1.KuryrPort, opts v1.UpdateOptions) (*v1alpha1.KuryrPort, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.KuryrPort, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.KuryrPortList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KuryrPort, err error)
	KuryrPortExpansion
}

// kuryrPorts implements KuryrPortInterface
type kuryrPorts struct {
	client rest.Interface
	ns     string
}

// newKuryrPorts returns a KuryrPorts
func newKuryrPorts(c *OpenstackV1alpha1Client, namespace string) *kuryrPorts {
	return &kuryrPorts{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the kuryrPort, and returns the corresponding kuryrPort object, and an error if there is any.
func (c *kuryrPorts) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KuryrPort, err error) {
	result = &v1alpha1.KuryrPort{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kuryrports").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KuryrPorts that match those selectors.
func (c *kuryrPorts) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KuryrPortList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.KuryrPortList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kuryrports").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kuryrPorts.
func (c *kuryrPorts) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("kuryrports").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a kuryrPort and creates it.  Returns the server's representation of the kuryrPort, and an error, if there is any.
func (c *kuryrPorts) Create(ctx context.Context, kuryrPort *v1alpha1.KuryrPort, opts v1.CreateOptions) (result *v1alpha1.KuryrPort, err error) {
	result = &v1alpha1.KuryrPort{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("kuryrports").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kuryrPort).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a kuryrPort and updates it. Returns the server's representation of the kuryrPort, and an error, if there is any.
func (c *kuryrPorts) Update(ctx context.Context, kuryrPort *v1alpha1.KuryrPort, opts v1.UpdateOptions) (result *v1alpha1.KuryrPort, err error) {
	result = &v1alpha1.KuryrPort{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kuryrports").
		Name(kuryrPort.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kuryrPort).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *kuryrPorts) UpdateStatus(ctx context.Context, kuryrPort *v1alpha1.KuryrPort, opts v1.UpdateOptions) (result *v1alpha1.KuryrPort, err error) {
	result = &v1alpha1.KuryrPort{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kuryrports").
		Name(kuryrPort.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kuryrPort).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the kuryrPort and deletes it. Returns an error if one occurs.
func (c *kuryrPorts) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kuryrports").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kuryrPorts) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kuryrports").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched kuryrPort.
func (c *kuryrPorts) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KuryrPort, err error) {
	result = &v1alpha1.KuryrPort{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("kuryrports").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
