/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	v1alpha1 "projectkuryr/kuryr/pkg/apis/openstack/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKuryrPorts implements KuryrPortInterface
type FakeKuryrPorts struct {
	Fake *FakeOpenstackV1alpha1
	ns   string
}

var kuryrportsResource = schema.GroupVersionResource{Group: "openstack.org", Version: "v1alpha1", Resource: "kuryrports"}

var kuryrportsKind = schema.GroupVersionKind{Group: "openstack.org", Version: "v1alpha1", Kind: "KuryrPort"}

// Get takes name of the kuryrPort, and returns the corresponding kuryrPort object, and an error if there is any.
func (c *FakeKuryrPorts) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KuryrPort, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(kuryrportsResource, c.ns, name), &v1alpha1.KuryrPort{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KuryrPort), err
}

// List takes label and field selectors, and returns the list of KuryrPorts that match those selectors.
func (c *FakeKuryrPorts) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KuryrPortList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(kuryrportsResource, kuryrportsKind, c.ns, opts), &v1alpha1.KuryrPortList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KuryrPortList{ListMeta: obj.(*v1alpha1.KuryrPortList).ListMeta}
	for _, item := range obj.(*v1alpha1.KuryrPortList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kuryrPorts.
func (c *FakeKuryrPorts) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(kuryrportsResource, c.ns, opts))

}

// Create takes the representation of a kuryrPort and creates it.  Returns the server's representation of the kuryrPort, and an error, if there is any.
func (c *FakeKuryrPorts) Create(ctx context.Context, kuryrPort *v1alpha1.KuryrPort, opts v1.CreateOptions) (result *v1alpha1.KuryrPort, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(kuryrportsResource, c.ns, kuryrPort), &v1alpha1.KuryrPort{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KuryrPort), err
}

// Update takes the representation of a kuryrPort and updates it. Returns the server's representation of the kuryrPort, and an error, if there is any.
func (c *FakeKuryrPorts) Update(ctx context.Context, kuryrPort *v1alpha1.KuryrPort, opts v1.UpdateOptions) (result *v1alpha1.KuryrPort, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(kuryrportsResource, c.ns, kuryrPort), &v1alpha1.KuryrPort{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KuryrPort), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKuryrPorts) UpdateStatus(ctx context.Context, kuryrPort *v1alpha1.KuryrPort, opts v1.UpdateOptions) (*v1alpha1.KuryrPort, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(kuryrportsResource, "status", c.ns, kuryrPort), &v1alpha1.KuryrPort{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KuryrPort), err
}

// Delete takes name of the kuryrPort and deletes it. Returns an error if one occurs.
func (c *FakeKuryrPorts) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(kuryrportsResource, c.ns, name), &v1alpha1.KuryrPort{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKuryrPorts) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(kuryrportsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.KuryrPortList{})
	return err
}

// Patch applies the patch and returns the patched kuryrPort.
func (c *FakeKuryrPorts) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KuryrPort, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(kuryrportsResource, c.ns, name, pt, data, subresources...), &v1alpha1.KuryrPort{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KuryrPort), err
}
