/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	openstackv1alpha1 "projectkuryr/kuryr/pkg/apis/openstack/v1alpha1"
	versioned "projectkuryr/kuryr/pkg/client/clientset/versioned"
	internalinterfaces "projectkuryr/kuryr/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "projectkuryr/kuryr/pkg/client/listers/openstack/v1alpha1"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// KuryrNetworkPolicyInformer provides access to a shared informer and lister for
// KuryrNetworkPolicies.
type KuryrNetworkPolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.KuryrNetworkPolicyLister
}

type kuryrNetworkPolicyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewKuryrNetworkPolicyInformer constructs a new informer for KuryrNetworkPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKuryrNetworkPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredKuryrNetworkPolicyInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredKuryrNetworkPolicyInformer constructs a new informer for KuryrNetworkPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredKuryrNetworkPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OpenstackV1alpha1().KuryrNetworkPolicies(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OpenstackV1alpha1().KuryrNetworkPolicies(namespace).Watch(context.TODO(), options)
			},
		},
		&openstackv1alpha1.KuryrNetworkPolicy{},
		resyncPeriod,
		indexers,
	)
}

func (f *kuryrNetworkPolicyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredKuryrNetworkPolicyInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *kuryrNetworkPolicyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&openstackv1alpha1.KuryrNetworkPolicy{}, f.defaultInformer)
}

func (f *kuryrNetworkPolicyInformer) Lister() v1alpha1.KuryrNetworkPolicyLister {
	return v1alpha1.NewKuryrNetworkPolicyLister(f.Informer().GetIndexer())
}
